<?php
use Laminas\View\View;

/**
 * @var $this View
 */
?>
<h1>Incluir Imoveis</h1>
<br>
<form method="post" action="<?=$this->url('cadastros',[
'controller' => 'imoveis',
'action' => 'gravar'    
])?>">
Tipo: <input type="text" name="tipo" autofocus="autofocus">
<br>
Tamanho em m²: <input type="number" name="tamanho" autofocus="autofocus">
<br>
Valor: <input type="number" name="valor" autofocus="autofocus">

<br><br>
<input type="submit" value="Gravar">
</form>

<br>
<a href="<?=$this->url('cadastros',[
'controller' => 'imoveis'    
])?>">Voltar</a>
