<?php
use Laminas\View\View;

/**
 * @var $this View
 */
?>
<h1>Incluir Imoveis</h1>
<br>
<form method="post" action="<?=$this->url('cadastros',[
'controller' => 'imoveis',
'action' => 'gravar'    
])?>">
Tipo: <input type="text" name="tipo" autofocus="autofocus" value="<?=$this->imoveis->tipo?>">
<input type="hidden" name="registro" value="<?=$this->imoveis->registro?>">
<br>
Tamanho em m²: <input type="number" name="tamanho" autofocus="autofocus" value="<?=$this->imoveis->tamanho?>">
<br>
Valor: <input type="number" name="valor" autofocus="autofocus" value="<?=$this->imoveis->valor?>">

<br><br>
<input type="submit" value="Gravar">
</form>

<br>
<a href="<?=$this->url('cadastros',[
'controller' => 'imoveis'    
])?>">Voltar</a>
