<?php
/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>
<h1>Cadastro de Imoveis</h1>
<p><a href="<?=$this->url('cadastros',[
    'controller' => 'imoveis',
    'action' => 'editar'
])?>">Novo Imovel</a></p>
<table>
<thead>
<tr>
<th>Registro</th>
<th>Tipo</th>
<th>Metragem</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
    <?=$this->partialLoop('imoveis.phtml',$this->imoveis)?>
</tbody>
</table>
<a href="<?=$this->url('cadastros')?>">Voltar</a>